name: Conditional Amplify Deploy

on:
  push:
    branches:
      - new

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIAQ4723WKL5SYX4FMV }}
          aws-secret-access-key: ${{ secrets.F/GuF6U4FI77cXM+mpZWMIbVJNNCrmuhMnE57uXr }}
          aws-region: ap-south-1

      - name: Deploy to Amplify
        run: |
          amplify pull --yes --appId d3730jg75e86kf --envName new
          amplify publish --yes
